// Copyright (C) 2026 Piers Finlayson <piers@piers.rocks>
//
// MIT License

// Builds signing-keys.json into the crate as Rust source that
// SignerTable::built_in() includes.
//
// src/signers/wire.rs decodes the file. The runtime parser uses the same
// module so a file the parser would refuse fails the build. Checking its
// public keys and proofs needs a signature library so the crate's tests check
// them instead.

extern crate alloc;

use std::env;
use std::fmt::Write;
use std::fs;
use std::path::Path;

// The build script decodes and never verifies so it doesn't use all of the
// module.
#[allow(dead_code)]
#[path = "src/signers/wire.rs"]
mod wire;

use wire::{Entry, Status};

fn main() {
    println!("cargo:rerun-if-changed=signing-keys.json");
    println!("cargo:rerun-if-changed=tests/fixtures/signing-keys.json");
    println!("cargo:rerun-if-changed=src/signers/wire.rs");

    let out_dir = env::var("OUT_DIR").unwrap();
    let out_dir = Path::new(&out_dir);

    generate("signing-keys.json", &out_dir.join("built_in_signers.rs"));

    // The unit test in src/signers/mod.rs compares this with the parser's
    // decoding of the fixture. The fixture has a signer of every status.
    generate(
        "tests/fixtures/signing-keys.json",
        &out_dir.join("fixture_signers.rs"),
    );
}

// Write the table in `source` to `dest` as a `&[Signer]` expression.
fn generate(source: &str, dest: &Path) {
    let json = fs::read(source).unwrap_or_else(|e| panic!("Failed to read {source}: {e}"));
    let entries = wire::decode_table(&json).unwrap_or_else(|e| panic!("{source}: {e}"));

    let mut out = format!("// Generated by build.rs from {source}.\n&[\n");
    for entry in &entries {
        write_signer(&mut out, entry);
    }
    out.push_str("]\n");

    fs::write(dest, out).unwrap_or_else(|e| panic!("Failed to write {}: {e}", dest.display()));
}

// Write one signer as a struct expression. Its paths are absolute so it means
// the same wherever it is included.
fn write_signer(out: &mut String, entry: &Entry) {
    let status = match &entry.status {
        Status::Current => "crate::signers::wire::Status::Current".to_string(),
        Status::Retired { record: None } => {
            "crate::signers::wire::Status::Retired { record: None }".to_string()
        }
        Status::Retired {
            record: Some(record),
        } => format!(
            "crate::signers::wire::Status::Retired {{ record: Some(crate::signers::wire::Record {{ \
             url: alloc::borrow::Cow::Borrowed({:?}), sha256: {:?} }}) }}",
            record.url, record.sha256,
        ),
    };
    // Debug formatting writes a string as an escaped Rust literal.
    writeln!(
        out,
        "    crate::signers::Signer {{ id: {}, name: alloc::borrow::Cow::Borrowed({:?}), \
         public_key: {:?}, status: {status} }},",
        entry.id, entry.name, entry.public_key,
    )
    .unwrap();
}
