# Top level Makefile for One ROM
#
# Running this Makefile will generate the One ROM firmware binary in $BUILD_DIR
# according to the settings below.

VERSION_MAJOR := 0
VERSION_MINOR := 7
VERSION_PATCH := 0
BUILD_NUMBER := 1
GIT_COMMIT := $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
export VERSION_MAJOR VERSION_MINOR VERSION_PATCH BUILD_NUMBER GIT_COMMIT

FIRMWARE_DIR := firmware
BUILD_DIR := $(FIRMWARE_DIR)/build

# probe-rs Chip ID
PROBE_RS_CHIP_ID=RP235X

# Device flash base
FLASH_BASE=0x10000000

#
# Settings
#
# Use these to specify your hardware variant and the ROM images and
# configuration.
#
#
# Development and debug settings
#
# It is recommended to leave these settings as is unless you are developing or
# debugging the One ROM firmware.
#
# However, if you are having problems with the One ROM firmware, you may want to
# disable any enabled features.
#

# Boot logging configuration
#
# Outputs diagnostics boot messages via SWD during the boot process.
#
# If you are using the ROM as a boot ROM in a machine with a very short reset
# timer, you may want to disable this.

BOOT_LOGGING ?= 0
# BOOT_LOGGING ?= 1

# Plugin logging configuration
#
# Enables logs from plugins that support it.

PLUGIN_LOGGING ?= 0
# PLUGIN_LOGGING ?= 1

# Main loop logging configuration
#
# This option enables/disabld logging within main_loop (see sdrr.rom_impl.c).
#
# It does not loop after every byte is served - that is enabled/disabled via
# MAIN_LOOP_ONE_SHOT.
#
# BOOT_LOGGING and MAIN_LOOP_LOGGING are required for this option to work.

MAIN_LOOP_LOGGING ?= 0
#MAIN_LOOP_LOGGING ?= 1

# Main loop one shot logging
#
# This option outputs logs after every byte is retrieved from the ROM.  While
# the main loop that processes the chip select and retrieves ROM data remanins
# functional, there is a gap between the CS line being released, and the ROM
# detecting the next CS activation - to make these logs.
#
# Therefore, with this option, the ROM will not meet its timing requirements,
# and it is not recommended to use this option unless you are debugging the
# ROM code.
#
# BOOT_LOGGING is required for this option to work.

MAIN_LOOP_ONE_SHOT ?= 0
# MAIN_LOOP_ONE_SHOT ?= 1

# Debug logging
#
# More extensive logging than the boot and main loop logging options.
#
# May overwhelm the SWD interface, meaning logs are dropped.
#
# This is not recommended for normal operation, but may be useful for debugging

DEBUG_LOGGING ?= 0
#DEBUG_LOGGING ?= 1

# Frequency
#
# Target frequency of the processor
# Leave blank to use the max frequency of the chip:
# - RP2350: 150MHz
#
# Your mileage may vary.  Faster machines will require the device to operate
# at higher frequencies.  Lower clock frequencies will cause One ROM to draw less
# power.
#
# It is suggested to leave this blank (i.e. use the maximum frequency) for most
# applications, and only dial it down if you are trying to reduce power
# consumption.

# FREQ ?= 30

# Output directory
#
# Directory to store intermediate files which are autogenerated during the
# build process.
GEN_OUTPUT_DIR ?= firmware/generated

# Cargo profile
#
# Whether to run cargo as release or debug.
# Needs to be blank for debug, because cargo.
CARGO_PROFILE ?= release

# Extra C Flags
#
# Use to pass extra flags into One ROM's compile stage.
#
# For example this enables the C main loop test function/
# EXTRA_C_FLAGS ?= -DC_MAIN_LOOP

EXTRA_C_FLAGS ?=


# Board - e.g. fire-32-a
#
# Only required when building the firmware using C-based metadata

BOARD ?= 


# Config - e.g. onerom-config/c64.json
#
# Only required when building the firmware using C-based metadata

CONFIG ?=

#
# End of settings
#

COLOUR_YELLOW := $(shell echo -e '\033[33m')
COLOUR_RESET := $(shell echo -e '\033[0m')
COLOUR_RED := $(shell echo -e '\033[31m')

ifneq ($(SUPPRESS_OUTPUT),1)
  $(info ==========================================)
  $(info Building One ROM v$(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_PATCH))
  $(info ==========================================)
  $(info One ROM Makefile env settings:)
endif

# Sort out binary prefix
BIN_PREFIX=onerom-rp235x

# Extra C flags
ifneq ($(EXTRA_C_FLAGS),)
ifneq ($(SUPPRESS_OUTPUT),1)
  $(info - EXTRA_C_FLAGS=$(EXTRA_C_FLAGS))
endif
endif

# Set FREQ_FLAG based on FREQ variable
ifeq ($(FREQ),)
  FREQ_FLAG =
else
ifneq ($(SUPPRESS_OUTPUT),1)
  $(info - FREQ=$(FREQ))
endif
  FREQ_FLAG = --freq $(FREQ)
endif

ifeq ($(CONFIG),)
  CONFIG_FLAG =
else
ifneq ($(SUPPRESS_OUTPUT),1)
  $(info - CONFIG=$(CONFIG))
endif
  CONFIG_FLAG = --config $(CONFIG)
endif

ifeq ($(BOARD),)
  BOARD_FLAG =
else
ifneq ($(SUPPRESS_OUTPUT),1)
  $(info - BOARD=$(BOARD))
endif
  BOARD_FLAG = --board $(BOARD)
endif

# Set up CARGO_TARGET_DIR
ifeq ($(CARGO_PROFILE),)
  CARGO_TARGET_DIR := rust/target/debug
else
  CARGO_TARGET_DIR := rust/target/$(CARGO_PROFILE)
endif
ifneq ($(SUPPRESS_OUTPUT),1)
$(info - CARGO_TARGET_DIR=$(CARGO_TARGET_DIR))
endif

ifneq ($(ARGS),)
ifneq ($(SUPPRESS_OUTPUT),1)
$(info - ARGS=$(ARGS))
endif
endif

ifneq ($(SUPPRESS_OUTPUT),1)
$(info -----)
endif

.PHONY: all clean clean-firmware clean-firmware-build firmware run flash test test-emu test-api generated clean-generated fw-config-gen libonerom-test gen-config clean-gen-config clean-libonerom-test

all: firmware
	@echo "=========================================="
	@echo "One ROM firmware build complete:"
	@echo "- firmware files are in $(BUILD_DIR)/"
	@echo "-----"
	@ls -ltr $(BUILD_DIR)/$(BIN_PREFIX).elf
	@ls -ltr $(BUILD_DIR)/$(BIN_PREFIX).bin
	-@ls -ltr $(BUILD_DIR)/$(BIN_PREFIX).uf2
	@echo "=========================================="

generated: 
	@echo "=========================================="
	@echo "Building onerom-metadata, to generate metadata header file"
	@echo "-----"
	@cd rust && cargo build --$(CARGO_PROFILE) -p onerom-metadata

fw-config-gen:
	@cd rust && cargo build --$(CARGO_PROFILE) -p fw-config-gen --quiet

firmware: generated
	@echo "=========================================="
	@echo "Building One ROM firmware - RP235X"
	@echo "-----"
	@GEN_OUTPUT_DIR=$(GEN_OUTPUT_DIR) EXTRA_C_FLAGS="$(EXTRA_C_FLAGS)" BIN_PREFIX="$(BIN_PREFIX)" DEBUG_LOGGING=$(DEBUG_LOGGING) PLUGIN_LOGGGING=$(PLUGIN_LOGGING) make --no-print-directory -C $(FIRMWARE_DIR)
	@if command -v picotool >/dev/null 2>&1; then \
		picotool uf2 convert $(BUILD_DIR)/$(BIN_PREFIX).bin $(BUILD_DIR)/$(BIN_PREFIX).uf2; \
	else \
		echo "Warning: picotool not found, skipping UF2 conversion"; \
	fi

run: firmware info
	@echo "=========================================="
	@echo "Flash One ROM firmware to device and attach to logging:"
	@echo "-----"
	@probe-rs run --chip $(PROBE_RS_CHIP_ID) $(BUILD_DIR)/$(BIN_PREFIX).elf

flash: firmware info
	@echo "=========================================="
	@echo "Flash One ROM firmware to device:"
	@echo "-----"
	@probe-rs download --chip $(PROBE_RS_CHIP_ID) --binary-format bin --base-address $(FLASH_BASE) $(BUILD_DIR)/$(BIN_PREFIX).bin

test: firmware
	@echo "=========================================="
	@echo "Building tests to:"
	@echo "- verify generated firmware ROM images"
	@echo "-----"
	@GEN_OUTPUT_DIR=$(GEN_OUTPUT_DIR) EXTRA_C_FLAGS="$(EXTRA_C_FLAGS)" make --no-print-directory -C test
	@echo "=========================================="
	@echo "Running tests to:"
	@echo "- verify generated firmware ROM images"
	@echo "-----"
	test/build/image-test
	@echo "-----"
	@echo "Tests completed"

gen-config: fw-config-gen
	@echo "=========================================="
	@echo "Generating C-based metadata"
	@echo "-----"
	@$(CARGO_TARGET_DIR)/fw-config-gen \
		$(CONFIG_FLAG) \
		--version $(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_PATCH).$(BUILD_NUMBER) \
		$(BOARD_FLAG) \
		--output $(GEN_OUTPUT_DIR)/gen-config.c

test-emu: gen-config
	@echo "=========================================="
	@echo "Running One ROM emulator tests"
	@echo "-----"
	@BASE_DIR=$(CURDIR) CONFIG=$(CONFIG) BOARD=$(BOARD) cargo run --manifest-path rust/Cargo.toml -p onerom-fw-tester --bin pio-tester --quiet

test-api: gen-config
	@echo "=========================================="
	@echo "Running One ROM emulator tests"
	@echo "-----"
	@BASE_DIR=$(CURDIR) CONFIG=$(CONFIG) BOARD=$(BOARD) cargo run --manifest-path rust/Cargo.toml -p onerom-fw-tester --bin plugin-api-tester --quiet

libonerom-test: gen-config
	@echo "=========================================="
	@echo "Building libonerom-test"
	@echo "-----"
	EXTRA_C_FLAGS="$(EXTRA_C_FLAGS)" make --no-print-directory -C $(FIRMWARE_DIR) -f test.mk
	@echo "-----"
	@echo "Done building libonerom-test"

-include $(GEN_OUTPUT_DIR)/generated.mk

clean-firmware-build:
	+cd $(FIRMWARE_DIR) && make clean-build

clean-firmware: clean-generated
	+cd $(FIRMWARE_DIR) && make clean

clean-generated:
	cd rust && cargo clean -p onerom-metadata
	cd firmware/generated && rm -f onerom_metadata.h

clean-rust:
	cd rust && cargo clean

clean-gen-config:
	cd firmware/generated && rm -f gen-config.c

clean-libonerom-test: clean-gen-config
	+cd $(FIRMWARE_DIR) && make -f test.mk clean-test

clean: clean-firmware clean-rust clean-generated clean-gen-config clean-libonerom-test
