[package]
name = "onerom-fw"
version = "0.4.0"
edition = "2024"
authors = ["Piers Finlayson <piers@piers.rocks>"]
license = "MIT"
description = "Firmware generator for One ROM - the flexible retro ROM replacement"
repository = "https://github.com/piersfinlayson/one-rom"
homepage = "https://onerom.org"
documentation = "https://docs.rs/onerom-fw"
keywords = ["retro", "rom", "commodore", "embedded"]
categories = ["embedded", "hardware-support"]

[lib]
name = "onerom_fw"
path = "src/lib.rs"

[dependencies]
onerom-config = { workspace = true }
onerom-gen = { workspace = true }

base64 = { version = "0.22" }
bytes = "1.10"
hex = { version = "0.4" }
log = "0.4"
reqwest = { version = "0.12", default-features = false, features = ["json", "charset", "blocking", "rustls-tls"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
sha2 = "0.11"
zip = "6.0"

[lints]
workspace = true
