[package]
name = "onerom-signing-server"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Piers Finlayson <piers@piers.rocks>"]
description = "Signs One ROM commissioning instances."
repository = "https://github.com/piersfinlayson/one-rom"
homepage = "https://onerom.org"
publish = false

[dependencies]
onerom-config = { workspace = true }
onerom-metadata = { workspace = true }

clap = { version = "4", features = ["derive"] }
ed25519-dalek = { version = "3", features = ["pem"] }
env_logger = "0.11"
http-body-util = "0.1"
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio"] }
log = "0.4"
pkcs8 = { version = "0.11", features = ["encryption", "pem"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["fs", "macros", "net", "process", "rt-multi-thread", "sync", "time"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["logging", "ring", "tls12"] }

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["io-util"] }

[lints]
workspace = true
