// Copyright (c) 2026 Piers Finlayson <piers@piers.rocks>
//
// MIT licence

use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

use onerom_config::hw::{Board, MODELS};
use onerom_config::mcu::Family;
use onerom_lab_metadata::LAB_METADATA_SIZE;
use onerom_metadata::ONEROM_INFO_OFFSET;

fn main() {
    // Run on every build, so the build date and commit are always current.
    // Cargo reruns a script whose rerun-if-changed path is missing, and nothing
    // creates this path.
    println!("cargo:rerun-if-changed=.rerun-every-build");
    println!("cargo:rerun-if-env-changed=BOARD");

    // Set up linking
    println!("cargo:rustc-link-arg=-v");
    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");

    // Re-run this build script of DEFMT_LOG changes.
    println!("cargo:rerun-if-env-changed=DEFMT_LOG");

    // Create a map file
    let out_dir = env::var("OUT_DIR").unwrap();
    println!("cargo:rustc-link-arg=-Map={out_dir}/output.map");
    // Generate memory.x
    generate_rp2350_memory_x();

    // Generate what Lab's metadata needs from the build
    generate_build_info();
}

/// Write `build_info.rs` into OUT_DIR, for `src/metadata.rs` to include.
fn generate_build_info() {
    let baked_board = match baked_board() {
        Some(board) => format!("Some(Board::{board:?})"),
        None => "None".to_string(),
    };
    let version = |part: &str| -> u16 {
        env::var(format!("CARGO_PKG_VERSION_{part}"))
            .unwrap()
            .parse()
            .unwrap()
    };
    let (major, minor, patch) = (version("MAJOR"), version("MINOR"), version("PATCH"));
    let build_date = build_date();
    let commit = commit();

    // Every board by name.  Board is non_exhaustive, so the match also needs a
    // wildcard.  If the wildcard ever matches a board, the workspace's
    // wildcard_enum_match_arm lint fails Lab's clippy run.
    //
    // Each name is a static in Lab's metadata block because both hw_rev fields
    // point at one and a host reads only that block.
    let mut statics = String::new();
    let mut names = String::new();
    for (index, board) in MODELS.iter().flat_map(|model| model.boards()).enumerate() {
        let bytes = format!("{}\0", board.name());
        statics += &format!(
            "#[unsafe(link_section = \".onerom_lab_metadata\")]\n\
             static BOARD_NAME_{index}: [u8; {}] = *b{bytes:?};\n",
            bytes.len()
        );
        names += &format!("        Board::{board:?} => &BOARD_NAME_{index},\n");
    }

    let code = format!(
        r#"// @generated by rust/lab/build.rs

/// The board `BOARD` named when this image was built, if any.
pub const BAKED_BOARD: Option<Board> = {baked_board};

// Lab's version, from its Cargo.toml.
pub const VERSION_MAJOR: u16 = {major};
pub const VERSION_MINOR: u16 = {minor};
pub const VERSION_PATCH: u16 = {patch};

/// When this image was built, as UTC.
pub const BUILD_DATE: &CStr = c{build_date:?};

/// The commit this image was built from.
pub const COMMIT: [u8; 8] = {commit:?};

{statics}
/// `board`'s name as a C string.
pub const fn board_c_name(board: Board) -> &'static CStr {{
    let name: &'static [u8] = match board {{
{names}        _ => unreachable!(),
    }};
    match CStr::from_bytes_with_nul(name) {{
        Ok(name) => name,
        Err(_) => unreachable!(),
    }}
}}
"#
    );

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("build_info.rs"), code).unwrap();
}

/// The board `BOARD` names, if any.  A name that isn't a Fire board fails the
/// build.
fn baked_board() -> Option<Board> {
    // scripts/flash.sh sets BOARD empty when given no board.
    let name = env::var("BOARD").ok().filter(|name| !name.is_empty())?;
    let board =
        Board::try_from_str(&name).unwrap_or_else(|| panic!("BOARD={name} is not a known board"));
    assert!(
        matches!(board.mcu_family(), Family::Rp2350),
        "BOARD={name} is not a Fire board, and Lab runs on Fire only"
    );
    Some(board)
}

/// The current UTC time, in the format One ROM's Makefile uses for its build
/// date.
fn build_date() -> String {
    chrono::Utc::now().format("%b %e %Y %H:%M:%SZ").to_string()
}

/// The short hash of the commit being built, as One ROM's Makefile gets it, or
/// "unknown" outside git.  Cut to seven characters so the terminating NUL fits
/// in the header's 8-byte field.
fn commit() -> [u8; 8] {
    let hash = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .filter(|output| output.status.success())
        .and_then(|output| String::from_utf8(output.stdout).ok())
        .map(|hash| hash.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string());

    let mut commit = [0; 8];
    let len = hash.len().min(commit.len() - 1);
    commit[..len].copy_from_slice(&hash.as_bytes()[..len]);
    commit
}

fn generate_rp2350_memory_x() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let memory_path = Path::new(&out_dir).join("memory.x");

    // onerom_info_t's offset in flash and the size limit of Lab's metadata
    // block come from the metadata schemas.
    let offset = format!(
        "ONEROM_INFO_OFFSET = {ONEROM_INFO_OFFSET:#X};\n\
         LAB_METADATA_SIZE = {LAB_METADATA_SIZE:#X};\n"
    );

    let memory_x = r#"
MEMORY {
    /*
     * The RP2350 has either external or internal flash.
     *
     * 2 MiB is a safe default here, although a Pico 2 has 4 MiB.
     */
    FLASH : ORIGIN = 0x10000000, LENGTH = 2048K
    /*
     * RAM consists of 8 banks, SRAM0-SRAM7, with a striped mapping.
     * This is usually good for performance, as it distributes load on
     * those banks evenly.
     */
    RAM : ORIGIN = 0x20000000, LENGTH = 512K
    /*
     * RAM banks 8 and 9 use a direct mapping. They can be used to have
     * memory areas dedicated for some specific job, improving predictability
     * of access times.
     * Example: Separate stacks for core0 and core1.
     */
    SRAM8 : ORIGIN = 0x20080000, LENGTH = 4K
    SRAM9 : ORIGIN = 0x20081000, LENGTH = 4K
}

SECTIONS {
    /* ### Boot ROM info
     *
     * Goes after .vector_table, to keep it in the first 4K of flash
     * where the Boot ROM (and picotool) can find it
     */
    .start_block : ALIGN(4)
    {
        __start_block_addr = .;
        KEEP(*(.start_block));
        KEEP(*(.boot_info));
    } > FLASH

    /* ### onerom_info_t
     *
     * At ONEROM_INFO_OFFSET in flash.
     */
    .onerom_info ORIGIN(FLASH) + ONEROM_INFO_OFFSET :
    {
        KEEP(*(.onerom_info));
    } > FLASH

    /* ### Lab's metadata block
     *
     * A host reads LAB_METADATA_SIZE bytes from onerom_info_t's metadata
     * pointer.  So the metadata header goes first and everything it and the
     * runtime structure point at follows.
     */
    .onerom_lab_metadata : ALIGN(4)
    {
        KEEP(*(.onerom_lab_metadata.header));
        KEEP(*(.onerom_lab_metadata));
    } > FLASH

} INSERT AFTER .vector_table;

ASSERT(ADDR(.start_block) + SIZEOF(.start_block) <= ADDR(.onerom_info),
       "The boot info overlaps onerom_info_t");
ASSERT(SIZEOF(.onerom_info) > 0, "onerom_info_t is missing from .onerom_info");
ASSERT(SIZEOF(.onerom_lab_metadata) <= LAB_METADATA_SIZE,
       "Lab's metadata block is larger than LAB_METADATA_SIZE");

/* move .text to start /after/ Lab's metadata block */
_stext = ADDR(.onerom_lab_metadata) + SIZEOF(.onerom_lab_metadata);

SECTIONS {
    /* ### Picotool 'Binary Info' Entries
     *
     * Picotool looks through this block (as we have pointers to it in our
     * header) to find interesting information.
     */
    .bi_entries : ALIGN(4)
    {
        /* We put this in the header */
        __bi_entries_start = .;
        /* Here are the entries */
        KEEP(*(.bi_entries));
        /* Keep this block a nice round size */
        . = ALIGN(4);
        /* We put this in the header */
        __bi_entries_end = .;
    } > FLASH
} INSERT AFTER .text;

SECTIONS {
    /* ### Boot ROM extra info
     *
     * Goes after everything in our program, so it can contain a signature.
     */
    .end_block : ALIGN(4)
    {
        __end_block_addr = .;
        KEEP(*(.end_block));
    } > FLASH

} INSERT AFTER .uninit;

PROVIDE(start_to_end = __end_block_addr - __start_block_addr);
PROVIDE(end_to_start = __start_block_addr - __end_block_addr);
    "#;

    fs::write(memory_path, offset + memory_x).unwrap();
    println!("cargo:rustc-link-search={out_dir}");
}
