name: CI Build

permissions:
  contents: write
  actions: read

on:
  workflow_dispatch:
  push:
    paths:
      - 'Makefile'
      - 'ci/**'
      - '!ci/docker/**'
      - 'firmware/**'
      - 'plugins/**'
      - 'rust/**'
      - 'old-config/**'
      - 'onerom-config/**'
      - '.github/**'
      - '!.github/workflows/release.yml'
      - '!**.md'
      - '!docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Makefile'
      - 'ci/**'
      - '!ci/docker/**'
      - 'firmware/**'
      - 'plugins/**'
      - 'rust/**'
      - 'old-config/**'
      - 'onerom-config/**'
      - '.github/**'
      - '!.github/workflows/release.yml'
      - '!**.md'
      - '!docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi libcurl4-openssl-dev libjson-c-dev libzip-dev make
        
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Rust wasm-pack
      run: cargo install wasm-pack

    - name: Run various Rust tests
      run: |
        export TOOLCHAIN=/usr/bin
        ci/rust-tests.sh

    - name: Build Rust docs
      run: |
        export TOOLCHAIN=/usr/bin
        ci/rust-docs.sh

    - name: Run One ROM emulator tests
      run: |
        export TOOLCHAIN=/usr/bin
        ci/test-emu.sh
      
    - name: Build firmware
      run: |
        export TOOLCHAIN=/usr/bin
        ci/build.sh ci

    - name: Build plugins
      run: |
        export TOOLCHAIN=/usr/bin
        make clean
        make
        make -C plugins/system/usb
        make -C plugins/user/activity
        make -C plugins/user/blink
        make -C plugins/user/host-control
        make -C plugins/user/rgb
        make -C firmware/ora/examples

    - name: Build tools
      run: |
        export TOOLCHAIN=/usr/bin
        ci/rust-tools.sh
